package com.prilepskiy.criptomanagerapp.domain.model.valute

import com.prilepskiy.criptomanagerapp.data.response.convertorResponse.valuteResponse

data class ValuteModel(
    val CharCode: String,
    val ID: String,
    val Name: String,
    val Nominal: Int,
    val NumCode: String,
    val Previous: Double,
    val Value: Double,
    val activate:Boolean
){
    companion object{
        fun fromList(data: valuteResponse):List<ValuteModel>
        {
            return mutableListOf(
                ValuteModel(
                data.Valute.AMD.CharCode,
                data.Valute.AMD.ID,
                data.Valute.AMD.Name,
                data.Valute.AMD.Nominal,
                data.Valute.AMD.NumCode,
                data.Valute.AMD.Previous,
                data.Valute.AMD.Value,
                activate = false,
                ),
                ValuteModel(
                    data.Valute.AUD.CharCode,
                    data.Valute.AUD.ID,
                    data.Valute.AUD.Name,
                    data.Valute.AUD.Nominal,
                    data.Valute.AUD.NumCode,
                    data.Valute.AUD.Previous,
                    data.Valute.AUD.Value,
                    activate = false,
            ),
                ValuteModel(
                    data.Valute.AZN.CharCode,
                    data.Valute.AZN.ID,
                    data.Valute.AZN.Name,
                    data.Valute.AZN.Nominal,
                    data.Valute.AZN.NumCode,
                    data.Valute.AZN.Previous,
                    data.Valute.AZN.Value,
                    activate = false,
                ),
                ValuteModel(
                    data.Valute.BGN.CharCode,
                    data.Valute.BGN.ID,
                    data.Valute.BGN.Name,
                    data.Valute.BGN.Nominal,
                    data.Valute.BGN.NumCode,
                    data.Valute.BGN.Previous,
                    data.Valute.BGN.Value,
                    activate = false,
                ),
                ValuteModel(
                    data.Valute.BRL.CharCode,
                    data.Valute.BRL.ID,
                    data.Valute.BRL.Name,
                    data.Valute.BRL.Nominal,
                    data.Valute.BRL.NumCode,
                    data.Valute.BRL.Previous,
                    data.Valute.BRL.Value,
                    activate = false,
                ),
                ValuteModel(
                    data.Valute.BYN.CharCode,
                    data.Valute.BYN.ID,
                    data.Valute.BYN.Name,
                    data.Valute.BYN.Nominal,
                    data.Valute.BYN.NumCode,
                    data.Valute.BYN.Previous,
                    data.Valute.BYN.Value,
                    activate = false,
                ),  ValuteModel(
                    data.Valute.CAD.CharCode,
                    data.Valute.CAD.ID,
                    data.Valute.CAD.Name,
                    data.Valute.CAD.Nominal,
                    data.Valute.CAD.NumCode,
                    data.Valute.CAD.Previous,
                    data.Valute.CAD.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.CHF.CharCode,
                    data.Valute.CHF.ID,
                    data.Valute.CHF.Name,
                    data.Valute.CHF.Nominal,
                    data.Valute.CHF.NumCode,
                    data.Valute.CHF.Previous,
                    data.Valute.CHF.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.CNY.CharCode,
                    data.Valute.CNY.ID,
                    data.Valute.CNY.Name,
                    data.Valute.CNY.Nominal,
                    data.Valute.CNY.NumCode,
                    data.Valute.CNY.Previous,
                    data.Valute.CNY.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.CZK.CharCode,
                    data.Valute.CZK.ID,
                    data.Valute.CZK.Name,
                    data.Valute.CZK.Nominal,
                    data.Valute.CZK.NumCode,
                    data.Valute.CZK.Previous,
                    data.Valute.CZK.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.DKK.CharCode,
                    data.Valute.DKK.ID,
                    data.Valute.DKK.Name,
                    data.Valute.DKK.Nominal,
                    data.Valute.DKK.NumCode,
                    data.Valute.DKK.Previous,
                    data.Valute.DKK.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.EUR.CharCode,
                    data.Valute.EUR.ID,
                    data.Valute.EUR.Name,
                    data.Valute.EUR.Nominal,
                    data.Valute.EUR.NumCode,
                    data.Valute.EUR.Previous,
                    data.Valute.EUR.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.GBP.CharCode,
                    data.Valute.GBP.ID,
                    data.Valute.GBP.Name,
                    data.Valute.GBP.Nominal,
                    data.Valute.GBP.NumCode,
                    data.Valute.GBP.Previous,
                    data.Valute.GBP.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.HKD.CharCode,
                    data.Valute.HKD.ID,
                    data.Valute.HKD.Name,
                    data.Valute.HKD.Nominal,
                    data.Valute.HKD.NumCode,
                    data.Valute.HKD.Previous,
                    data.Valute.HKD.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.HUF.CharCode,
                    data.Valute.HUF.ID,
                    data.Valute.HUF.Name,
                    data.Valute.HUF.Nominal,
                    data.Valute.HUF.NumCode,
                    data.Valute.HUF.Previous,
                    data.Valute.HUF.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.INR.CharCode,
                    data.Valute.INR.ID,
                    data.Valute.INR.Name,
                    data.Valute.INR.Nominal,
                    data.Valute.INR.NumCode,
                    data.Valute.INR.Previous,
                    data.Valute.INR.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.JPY.CharCode,
                    data.Valute.JPY.ID,
                    data.Valute.JPY.Name,
                    data.Valute.JPY.Nominal,
                    data.Valute.JPY.NumCode,
                    data.Valute.JPY.Previous,
                    data.Valute.JPY.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.KGS.CharCode,
                    data.Valute.KGS.ID,
                    data.Valute.KGS.Name,
                    data.Valute.KGS.Nominal,
                    data.Valute.KGS.NumCode,
                    data.Valute.KGS.Previous,
                    data.Valute.KGS.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.KRW.CharCode,
                    data.Valute.KRW.ID,
                    data.Valute.KRW.Name,
                    data.Valute.KRW.Nominal,
                    data.Valute.KRW.NumCode,
                    data.Valute.KRW.Previous,
                    data.Valute.KRW.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.KZT.CharCode,
                    data.Valute.KZT.ID,
                    data.Valute.KZT.Name,
                    data.Valute.KZT.Nominal,
                    data.Valute.KZT.NumCode,
                    data.Valute.KZT.Previous,
                    data.Valute.KZT.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.MDL.CharCode,
                    data.Valute.MDL.ID,
                    data.Valute.MDL.Name,
                    data.Valute.MDL.Nominal,
                    data.Valute.MDL.NumCode,
                    data.Valute.MDL.Previous,
                    data.Valute.MDL.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.NOK.CharCode,
                    data.Valute.NOK.ID,
                    data.Valute.NOK.Name,
                    data.Valute.NOK.Nominal,
                    data.Valute.NOK.NumCode,
                    data.Valute.NOK.Previous,
                    data.Valute.NOK.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.PLN.CharCode,
                    data.Valute.PLN.ID,
                    data.Valute.PLN.Name,
                    data.Valute.PLN.Nominal,
                    data.Valute.PLN.NumCode,
                    data.Valute.PLN.Previous,
                    data.Valute.PLN.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.RON.CharCode,
                    data.Valute.RON.ID,
                    data.Valute.RON.Name,
                    data.Valute.RON.Nominal,
                    data.Valute.RON.NumCode,
                    data.Valute.RON.Previous,
                    data.Valute.RON.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.SEK.CharCode,
                    data.Valute.SEK.ID,
                    data.Valute.SEK.Name,
                    data.Valute.SEK.Nominal,
                    data.Valute.SEK.NumCode,
                    data.Valute.SEK.Previous,
                    data.Valute.SEK.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.SGD.CharCode,
                    data.Valute.SGD.ID,
                    data.Valute.SGD.Name,
                    data.Valute.SGD.Nominal,
                    data.Valute.SGD.NumCode,
                    data.Valute.SGD.Previous,
                    data.Valute.SGD.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.TJS.CharCode,
                    data.Valute.TJS.ID,
                    data.Valute.TJS.Name,
                    data.Valute.TJS.Nominal,
                    data.Valute.TJS.NumCode,
                    data.Valute.TJS.Previous,
                    data.Valute.TJS.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.TMT.CharCode,
                    data.Valute.TMT.ID,
                    data.Valute.TMT.Name,
                    data.Valute.TMT.Nominal,
                    data.Valute.TMT.NumCode,
                    data.Valute.TMT.Previous,
                    data.Valute.TMT.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.TRY.CharCode,
                    data.Valute.TRY.ID,
                    data.Valute.TRY.Name,
                    data.Valute.TRY.Nominal,
                    data.Valute.TRY.NumCode,
                    data.Valute.TRY.Previous,
                    data.Valute.TRY.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.UAH.CharCode,
                    data.Valute.UAH.ID,
                    data.Valute.UAH.Name,
                    data.Valute.UAH.Nominal,
                    data.Valute.UAH.NumCode,
                    data.Valute.UAH.Previous,
                    data.Valute.UAH.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.USD.CharCode,
                    data.Valute.USD.ID,
                    data.Valute.USD.Name,
                    data.Valute.USD.Nominal,
                    data.Valute.USD.NumCode,
                    data.Valute.USD.Previous,
                    data.Valute.USD.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.UZS.CharCode,
                    data.Valute.UZS.ID,
                    data.Valute.UZS.Name,
                    data.Valute.UZS.Nominal,
                    data.Valute.UZS.NumCode,
                    data.Valute.UZS.Previous,
                    data.Valute.UZS.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.XDR.CharCode,
                    data.Valute.XDR.ID,
                    data.Valute.XDR.Name,
                    data.Valute.XDR.Nominal,
                    data.Valute.XDR.NumCode,
                    data.Valute.XDR.Previous,
                    data.Valute.XDR.Value,
                    activate = false),
                ValuteModel(
                    data.Valute.ZAR.CharCode,
                    data.Valute.ZAR.ID,
                    data.Valute.ZAR.Name,
                    data.Valute.ZAR.Nominal,
                    data.Valute.ZAR.NumCode,
                    data.Valute.ZAR.Previous,
                    data.Valute.ZAR.Value,
                    activate = false)


                )
        }
    }
}